/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP (1000) [Id]
      ,[Ime]
      ,[Prezime]
      ,[Adresa]
      ,[NetoPlata]
      ,[Bruto1]
      ,[PoreskoOslobodjenje]
      ,[PoreskaOsnovica]
      ,[PoreskaStopa]
      ,[PioZap]
      ,[ZdrOsigZap]
      ,[Nezaposlenost]
      ,[PioPoslodavac]
      ,[ZdrOsigPoslodavac]
      ,[Bruto2]
  FROM [PlataZadatakDB].[dbo].[Plata]