//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlataApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Plata
    {
        public int Id { get; set; }

        [Display(Name = "Ime")]
        [DataType(DataType.Text, ErrorMessage = "Unesite validno ime")]
        [StringLength(100, MinimumLength = 1)]
        [Required]
        public string Ime { get; set; }

        [Display(Name = "Prezime")]
        [DataType(DataType.Text, ErrorMessage = "Unesite validno prezime")]
        [StringLength(100, MinimumLength = 1)]
        [Required]
        public string Prezime { get; set; }

        [Display(Name = "Adresa")]
        [StringLength(100, MinimumLength = 1)]
        [Required]
        public string Adresa { get; set; }

        [Display(Name = "Iznos Neto Plate")]
        [Required]
        [Range(29429.00, 1000000, ErrorMessage = "Neto plata ne moze biti manja od minimalne zarade ili veca od 1000000.")]
        public decimal NetoPlata { get; set; }

        [Display(Name = "BRUTO 1")]
        [ReadOnly(true)]
        public decimal Bruto1 { get; set; }

        [Display(Name = "Iznos Poreskog Oslobodjenja")]
        [ReadOnly(true)]

        public decimal PoreskoOslobodjenje { get; set; }

        [Display(Name = "Poreska Osnovica")]
        [ReadOnly(true)]
        public decimal PoreskaOsnovica { get; set; }

        [Display(Name = "Iznos Poreske Stope")]
        [ReadOnly(true)]
        public decimal PoreskaStopa { get; set; }

        [Display(Name = "PIO na teret zaposlenog")]
        [ReadOnly(true)]
        public decimal PioZap { get; set; }

        [Display(Name = "Zdravstveno osiguranje na teret zaposlenog")]
        [ReadOnly(true)]
        public decimal ZdrOsigZap { get; set; }

        [Display(Name = "Nezaposlenost")]
        [ReadOnly(true)]
        public decimal Nezaposlenost { get; set; }

        [Display(Name = "PIO na teret poslodavca")]
        [ReadOnly(true)]
        public decimal PioPoslodavac { get; set; }

        [Display(Name = "Zdravstveno osiguranje na teret poslodavca")]
        [ReadOnly(true)]
        public decimal ZdrOsigPoslodavac { get; set; }

        [Display(Name = "BRUTO 2")]
        [ReadOnly(true)]
        public decimal Bruto2 { get; set; }
    }
}
